sudo: required
services:
  - docker

before_install:
  - docker build -t marceloalmeida/frontend -f Dockerfile.dev .

script:
  - docker run marceloalmeida/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "frontend"
  env: "frontend-env"
  bucket_name: "eleasticbeanstalk......"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY